# Generated by Django 6.0.2 on 2026-02-25 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signuprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande de prêt', 'verbose_name_plural': 'Demandes de prêt'},
        ),
        migrations.RemoveField(
            model_name='signuprequest',
            name='email',
        ),
        migrations.AddField(
            model_name='signuprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
