# Generated by Django 6.0.2 on 2026-02-26 05:55

import django.db.models.deletion
import signups.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0002_alter_signuprequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuprequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signup_requests', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='CreditDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', "En cours d'étude"), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='nouvelle', max_length=20)),
                ('montant', models.PositiveIntegerField(verbose_name='Montant (€)')),
                ('duree', models.PositiveIntegerField(verbose_name='Durée (mois)')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('nationalite', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('situation_familiale', models.CharField(choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)')], max_length=20)),
                ('situation_professionnelle', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('independant', 'Indépendant'), ('retraite', 'Retraité(e)'), ('chomage', 'Sans emploi'), ('autre', 'Autre')], max_length=20)),
                ('revenus_mensuels', models.PositiveIntegerField(verbose_name='Revenu net mensuel (€)')),
                ('autres_revenus', models.PositiveIntegerField(default=0, verbose_name='Autres revenus (€)')),
                ('charges_mensuelles', models.PositiveIntegerField(default=0, verbose_name='Charges (€)')),
                ('situation_logement', models.CharField(blank=True, choices=[('proprio_sans', 'Propriétaire sans crédit'), ('proprio_avec', 'Propriétaire avec crédit'), ('locataire', 'Locataire'), ('heberge', 'Hébergé à titre gratuit')], max_length=20)),
                ('motif', models.CharField(blank=True, choices=[('travaux', 'Travaux'), ('auto', 'Automobile'), ('sante', 'Santé'), ('vacances', 'Vacances'), ('rachat', 'Rachat crédit'), ('autre-motif', 'Autre')], max_length=20)),
                ('type_piece_identite', models.CharField(choices=[('cni', "Carte nationale d'identité"), ('passeport', 'Passeport'), ('titre', 'Titre de séjour')], default='cni', max_length=20)),
                ('signature', models.TextField(blank=True)),
                ('accepte_cgu', models.BooleanField(default=False)),
                ('certifie_exactitude', models.BooleanField(default=False)),
                ('accepte_marketing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_demands', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Demande de crédit',
                'verbose_name_plural': 'Demandes de crédit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemandDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_recto', "Pièce d'identité recto"), ('id_verso', "Pièce d'identité verso"), ('revenus', 'Justificatif de revenus'), ('domicile', 'Justificatif de domicile')], max_length=20)),
                ('fichier', models.FileField(max_length=255, upload_to=signups.models.demand_document_path)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='signups.creditdemand')),
            ],
            options={
                'verbose_name': 'Document de demande',
                'verbose_name_plural': 'Documents de demande',
            },
        ),
    ]
