# Generated by Django 6.0.2 on 2026-03-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0003_alter_signuprequest_user_creditdemand_demanddocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditdemand',
            name='signature',
        ),
    ]
