# Generated by Django 6.0.2 on 2026-03-24 11:52

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def seed_steps_and_backfill(apps, schema_editor):
    DemandProcessStep = apps.get_model("signups", "DemandProcessStep")
    CreditDemand = apps.get_model("signups", "CreditDemand")
    CreditDemandStepStatus = apps.get_model("signups", "CreditDemandStepStatus")

    defs = [
        (1, "reception", "Demande reçue", "Votre dossier a bien été transmis à notre équipe."),
        (2, "analyse", "Analyse du dossier", "Nous examinons votre demande et vos pièces justificatives."),
        (3, "decision", "Décision", "Finalisation de l'étude de votre dossier."),
        (4, "reponse", "Réponse", "Vous recevez la décision concernant votre prêt."),
    ]
    for order, code, title, desc in defs:
        DemandProcessStep.objects.get_or_create(
            code=code,
            defaults={
                "order": order,
                "title": title,
                "description": desc,
                "is_active": True,
            },
        )

    now = timezone.now()
    steps = list(DemandProcessStep.objects.filter(is_active=True).order_by("order", "pk"))
    if not steps:
        return

    for demande in CreditDemand.objects.all().iterator():
        if CreditDemandStepStatus.objects.filter(demande_id=demande.pk).exists():
            continue
        statut = demande.statut
        bulk = []
        for i, step in enumerate(steps):
            if statut in ("acceptee", "refusee"):
                st, completed_at = "completed", now
            elif statut == "en_cours":
                if i == 0:
                    st, completed_at = "completed", now
                elif i == 1:
                    st, completed_at = "in_progress", None
                else:
                    st, completed_at = "pending", None
            else:
                if i == 0:
                    st, completed_at = "completed", now
                elif i == 1:
                    st, completed_at = "in_progress", None
                else:
                    st, completed_at = "pending", None
            bulk.append(
                CreditDemandStepStatus(
                    demande_id=demande.pk,
                    step_id=step.pk,
                    status=st,
                    completed_at=completed_at,
                )
            )
        CreditDemandStepStatus.objects.bulk_create(bulk)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('signups', '0004_remove_creditdemand_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, help_text="Texte affiché au demandeur sous le titre de l'étape.", verbose_name='Description client')),
                ('is_active', models.BooleanField(default=True, help_text="Si coché, l'étape est utilisée pour les nouvelles demandes.", verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Étape du processus',
                'verbose_name_plural': 'Étapes du processus',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CreditDemandStepStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée')], default='pending', max_length=20, verbose_name='État')),
                ('client_message', models.TextField(blank=True, help_text='Optionnel : précision visible sur la page « Ma demande ».', verbose_name='Message au client')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_statuses', to='signups.creditdemand')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demand_statuses', to='signups.demandprocessstep')),
            ],
            options={
                'verbose_name': "Suivi d'étape",
                'verbose_name_plural': "Suivis d'étapes",
                'ordering': ['step__order', 'step__pk'],
                'constraints': [models.UniqueConstraint(fields=('demande', 'step'), name='unique_demande_step')],
            },
        ),
        migrations.RunPython(seed_steps_and_backfill, noop_reverse),
    ]
